const distillaries = [
    {
        id: 0,
        name: 'Lagavulin',
        region: 'Islay',
        date: 1816,
        favorite: false,
        featureDescription: '',
        pageDescription: '',
        pageImage: '',
    },

    {
        id: 1,
        name: 'Ardbeg',
        region: 'Islay',
        date: 1815,
        favorite: false,
        featureDescription: '',
        pageDescription: '',
        pageImage: '',
    },

    {
        id: 2,
        name: 'Bowmore',
        region: 'Islay',
        date: 1779,
        favorite: false,
        featureDescription: '',
        pageDescription: '',
        pageImage: '',
    },

    {
        id: 3,
        name: 'Bruichladdich',
        region: 'Islay',
        date: 1881,
        favorite: false,
        featureDescription: '',
        pageDescription: '',
        pageImage: '',
    },

    {
        id: 4,
        name: 'Bunnahabhain',
        region: 'Islay',
        date: 1881,
        favorite: false,
        featureDescription: '',
        pageDescription: '',
        pageImage: '',
    },

    {
        id: 5,
        name: 'Caol Ila',
        region: 'Islay',
        date: 1846,
        favorite: false,
        featureDescription: '',
        pageDescription: '',
        pageImage: '',
    },

    {
        id: 6,
        name: 'Kilchoman',
        region: 'Islay',
        date: 2005,
        favorite: false,
        featureDescription: '',
        pageDescription: '',
        pageImage: '',
    },

    {
        id: 7,
        name: 'Laphroaig',
        region: 'Islay',
        date: 1815,
        favorite: false,
        featureDescription: '',
        pageDescription: '',
        pageImage: '',
    },

    {
        id: 8,
        name: 'Glenlivet',
        region: 'Speyside',
        date: 1824,
        favorite: false,
        featureDescription: '',
        pageDescription: '',
        pageImage: '',
    },

    {
        id: 9,
        name: 'Glenfiddich',
        region: 'Speyside',
        date: 1886,
        favorite: false,
        featureDescription: '',
        pageDescription: '',
        pageImage: '',
    },

    {
        id: 10,
        name: 'Macallan',
        region: 'Speyside',
        date: 1824,
        favorite: false,
        featureDescription: '',
        pageDescription: '',
        pageImage: '',
    },

    {
        id: 11,
        name: 'Craigellachie',
        region: 'Speyside',
        date: 1891,
        favorite: false,
        featureDescription: '',
        pageDescription: '',
        pageImage: '',
    },

    {
        id: 12,
        name: 'Glen Moray',
        region: 'Speyside',
        date: 1831,
        favorite: false,
        featureDescription: '',
        pageDescription: '',
        pageImage: '',
    },

    {  
        id: 13,
        name: 'Glenfarclas',
        region: 'Speyside',
        date: 1865,
        favorite: false,
        featureDescription: '',
        pageDescription: '',
        pageImage: '',
    },
]